use core::str;
use esp_idf_svc::nvs::{EspNvs, EspNvsPartition, NvsDefault};
use std::sync::{LazyLock, RwLock};

use crate::config::NVS_PARTITION;

use super::CONFIG_NVS;

static DEVICE_NAME: LazyLock<RwLock<String>> = LazyLock::new(|| {
    let name;

    let nvs = CONFIG_NVS.read().unwrap();

    let mut buffer = [0u8; 16];
    if let Ok(Some(name)) = nvs.get_blob("device_name", &mut buffer) {
        if let Ok(name) = str::from_utf8(name) {
            return RwLock::new(name.into());
        }
    }

    unsafe {
        let mut mac = [0u8; 6];
        esp_idf_sys::esp_base_mac_addr_get(mac.as_mut_ptr());
        name = format!(
            "{:02X}{:02X}{:02X}{:02X}{:02X}{:02X}",
            mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]
        );
    };

    RwLock::new(name)
});

pub fn get_device_name() -> String {
    return DEVICE_NAME.read().unwrap().clone();
}

pub fn set_device_name(name: &str) {
    let mut nvs = CONFIG_NVS.write().unwrap();

    nvs.set_blob("device_name", name.as_bytes()).unwrap();
    let mut device_name = DEVICE_NAME.write().unwrap();
    *device_name = name.into();
}

// const NAMES: [&str; 256] = [
//     "Camdyn",
//     "Christan",
//     "Kris",
//     "Shaya",
//     "Hartley",
//     "Claudie",
//     "Ashtin",
//     "Krishna",
//     "Terryl",
//     "Marvis",
//     "Riley",
//     "Larkin",
//     "Kodi",
//     "Michal",
//     "Blair",
//     "Lavern",
//     "Ricci",
//     "Lavon",
//     "Emery",
//     "De",
//     "Seneca",
//     "Burnice",
//     "Ocean",
//     "Kendel",
//     "Amari",
//     "Kerry",
//     "Marlowe",
//     "Teegan",
//     "Baby",
//     "Jireh",
//     "Talyn",
//     "Kylin",
//     "Mckinley",
//     "Salem",
//     "Dallis",
//     "Jessie",
//     "Waverly",
//     "Ardell",
//     "Arden",
//     "Carey",
//     "Kamdyn",
//     "Jaziah",
//     "Tam",
//     "Demetrice",
//     "Emerson",
//     "Sonnie",
//     "Cameran",
//     "Kiran",
//     "Kalin",
//     "Devine",
//     "Evyn",
//     "Alva",
//     "Justice",
//     "Lakota",
//     "Tristyn",
//     "Ocie",
//     "Delane",
//     "Kailen",
//     "Vernie",
//     "Isa",
//     "Indiana",
//     "Shade",
//     "Marshell",
//     "Devyn",
//     "Natividad",
//     "Deniz",
//     "Parris",
//     "Dann",
//     "An",
//     "Ashten",
//     "Shai",
//     "Lian",
//     "Milan",
//     "Lorenza",
//     "Britain",
//     "Teddie",
//     "Jaydyn",
//     "Joell",
//     "Lorin",
//     "Micha",
//     "Arlyn",
//     "Ivory",
//     "Tru",
//     "Jae",
//     "Adair",
//     "Carrol",
//     "Kodie",
//     "Linn",
//     "Bao",
//     "Collen",
//     "Arie",
//     "Yael",
//     "Emari",
//     "Sol",
//     "Kimani",
//     "Robbie",
//     "Chi",
//     "Reilly",
//     "Lennie",
//     "Schyler",
//     "Cedar",
//     "Carlin",
//     "Landry",
//     "Sutton",
//     "True",
//     "Tenzin",
//     "Armani",
//     "Ryley",
//     "Amaree",
//     "Santana",
//     "Jaime",
//     "Divine",
//     "Ossie",
//     "Laramie",
//     "Dwan",
//     "Peyton",
//     "Rennie",
//     "Campbell",
//     "Drue",
//     "Jaelin",
//     "Remy",
//     "Allyn",
//     "Aries",
//     "Harley",
//     "Karsen",
//     "Jaylin",
//     "Jourdan",
//     "Cache",
//     "Stevie",
//     "Tylar",
//     "Daylin",
//     "Finley",
//     "Adel",
//     "Elisha",
//     "Kaidyn",
//     "Anay",
//     "Mycah",
//     "Jackie",
//     "Shamari",
//     "Toy",
//     "Verdell",
//     "Kenyatta",
//     "Casey",
//     "Jaedyn",
//     "Clair",
//     "Shia",
//     "Rio",
//     "Shea",
//     "Shay",
//     "Devonne",
//     "Kalani",
//     "Kriston",
//     "Jazz",
//     "Lavaughn",
//     "Rylin",
//     "Carrington",
//     "Jeryl",
//     "Ryen",
//     "Artie",
//     "Merlyn",
//     "Trinidad",
//     "Adi",
//     "Rowan",
//     "Camari",
//     "Rian",
//     "Payson",
//     "Britt",
//     "Tien",
//     "Jaidan",
//     "Taylen",
//     "Aven",
//     "Lin",
//     "Tai",
//     "Kary",
//     "Maxie",
//     "Lajuan",
//     "Rhyan",
//     "Aris",
//     "Ellery",
//     "Lannie",
//     "Dru",
//     "Mikah",
//     "Armoni",
//     "Leighton",
//     "Berlin",
//     "Aaryn",
//     "Ashby",
//     "Lexington",
//     "Codie",
//     "Charley",
//     "Yuri",
//     "Phoenix",
//     "Arin",
//     "Le",
//     "Nazareth",
//     "Finnley",
//     "Clemmie",
//     "Raynell",
//     "Jael",
//     "Mykah",
//     "Earlie",
//     "Barrie",
//     "Alpha",
//     "Onyx",
//     "Micaiah",
//     "Lashaun",
//     "Gentry",
//     "Thanh",
//     "Kaedyn",
//     "Golden",
//     "Frankie",
//     "Lyrik",
//     "Kaylon",
//     "Kareen",
//     "Dominque",
//     "Channing",
//     "Dakotah",
//     "Kendall",
//     "Adrean",
//     "Stephane",
//     "Aly",
//     "Azariah",
//     "Yuki",
//     "Ara",
//     "Marice",
//     "Pat",
//     "Charly",
//     "Samar",
//     "Codi",
//     "Sage",
//     "Kamari",
//     "Sloan",
//     "Braylin",
//     "Vinnie",
//     "Nieves",
//     "Quinn",
//     "Jammie",
//     "Berkeley",
//     "Jimi",
//     "Reese",
//     "Storm",
//     "Osiris",
//     "Oakley",
//     "Tory",
//     "Jule",
//     "Garnett",
//     "Halen",
//     "Deane",
//     "Brittan",
//     "Tobie",
//     "Skyler",
//     "Ellison",
//     "Vernell",
//     "Jody",
//     "Arnell",
//     "Berkley",
// ];

// // TODO: Improve this
// pub fn get_device_name() -> String {
//     // return "dirk".into();
//     let name;
//     unsafe {
//         let mut mac = [0u8; 6];
//         esp_idf_sys::esp_base_mac_addr_get(mac.as_mut_ptr());
//         name = format!(
//             "{}-{}-{}",
//             NAMES[mac[3] as usize], NAMES[mac[4] as usize], NAMES[mac[5] as usize]
//         );
//     };
//     name
// }
